concise version of original code done with anish
stfc/cloud-ops-tools pull request #10
Opened 2023-10-27 08:43 UTC by dev-0pz

made code smoother and making sure it worked by adding unit testing which still needs to be finished off

2023-10-27 09:18 UTC, meoflynn requested changes

2023-10-27 09:18 UTC, meoflynn commented on reverseforwardrecord/test_get_dns_record.py
> +def test_read_from_netbox_index_error(mock_load_workbook):
Could you add a docstring to this unit test?

2023-10-27 09:18 UTC, meoflynn commented on reverseforwardrecord/test_get_dns_record.py
> +def test_write_output_reversed_order():
Could you add a docstring to this unit test?

2023-10-27 09:18 UTC, meoflynn commented on reverseforwardrecord/test_get_dns_record.py
> +def test_write_output_non_reversed_order():
Could you add a docstring to this unit test?

2023-10-27 11:07 UTC, Koldstream requested changes

2023-10-27 11:07 UTC, Koldstream commented on reverseforwardrecord/get_dns_record.py
> +    # TODO argparse command line argument parsing
Is this still TODO?

2023-10-27 11:07 UTC, Koldstream commented on reverseforwardrecord/test_get_dns_record.py
> +# you only put anything in the parameters that are needed later in the mock test
I think these instructions should be removed?

2023-10-27 12:43 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +    # TODO argparse command line argument parsing
yea we still need to do it - for another PR

2023-10-30 15:59 UTC, meoflynn reviewed
Would it be possible to add `__pycache__` to the `.gitignore` file?

2023-10-31 09:37 UTC, khalford commented
On Megans .gitignore suggestion here are a few others to add in across any project you do.
`.idea/
__pycache__/
venv/
.vscode/`

2023-10-31 11:25 UTC, khalford requested changes

2023-10-31 11:25 UTC, khalford commented on .gitignore
You only need to put the top level directory in `.gitignore`.
`reverseforwardrecord/` Should tell git to ignore every file in that directory. That way you don't need to list each file.

2023-10-31 11:25 UTC, khalford commented on reverseforwardrecord/.github/workflows/get_dns_records.yaml
> +          cd reverseforwardrecord && pylint $(git ls-files *.py)
```suggestion
          cd reverseforwardrecord && pylint .
```
This should function the same and is less complicated. This is only a suggestion.

2023-10-31 11:25 UTC, khalford commented on reverseforwardrecord/get_dns_record.py
> +# create a new file for results to be returned into
Comments can be used for specific lines of code that are not self-explanatory. A description such as this can be kept in the Docstring.

2023-10-31 11:25 UTC, khalford commented on reverseforwardrecord/get_dns_record.py
> +    :return: None
If the function does not return anything I would leave out the `:return: None`. Alternatively, you can add a `return None` to the end of the function.

2023-10-31 11:25 UTC, khalford commented on reverseforwardrecord/get_dns_record.py
> +
```suggestion
return None
```

2023-10-31 11:25 UTC, khalford commented on reverseforwardrecord/get_dns_record.py
> +import socket
Socket is not used.

2023-10-31 11:25 UTC, khalford commented on reverseforwardrecord/get_dns_record.py
> +    workbook = load_workbook(filename=netbox_filepath)
I believe Pandas can handle Excel Workbooks itself. Using pandas to do this would remove the need for another library `openpyxl`

2023-10-31 11:25 UTC, khalford commented on reverseforwardrecord/requirements.txt
> +pip
Missing `pandas` and `openpyxl`

2023-10-31 13:29 UTC, Koldstream commented on reverseforwardrecord/get_dns_record.py
> +
I'd say if the function doesn't return anything then I might avoid this.

2023-11-01 08:02 UTC, meoflynn commented on .gitignore
Could you add `.idea` to this `.gitignore` file?

2023-11-01 10:31 UTC, dev-0pz commented on reverseforwardrecord/requirements.txt
> +pip
doesnt use it yet

2023-11-01 10:31 UTC, dev-0pz commented on reverseforwardrecord/get_dns_record.py
> +import socket
being developed

2023-11-01 10:33 UTC, dev-0pz commented on .gitignore
okay

2023-11-01 10:34 UTC, dev-0pz commented on .gitignore
will do

2023-11-01 12:23 UTC, khalford commented on reverseforwardrecord/requirements.txt
> +pip
You have both `pandas` and `openpyxl` imported in `get_dns_record.py`. These will need to be pip installed by anyone trying to run your code. Instead of the user having to figure out what packages they need to install to run your code, they can just install from the `requirements.txt`.

2023-11-03 11:08 UTC, dev-0pz commented on reverseforwardrecord/get_dns_record.py
> +    workbook = load_workbook(filename=netbox_filepath)
will learn to do that another time

2023-11-03 11:09 UTC, dev-0pz commented on reverseforwardrecord/get_dns_record.py
> +
changed it to return what it was meant to

2023-11-03 11:12 UTC, dev-0pz commented on reverseforwardrecord/requirements.txt
> +pip
will do later when pandas is used

2023-11-03 11:58 UTC, khalford approved these changes
LGTM

2023-11-06 09:34 UTC, closed without merging