Get dns records v3
stfc/cloud-ops-tools pull request #11
Opened 2023-11-06 09:30 UTC by dev-0pz

should be the one that ignores all of the files but otherwise I will need help doing this

2023-11-06 10:42 UTC, anish-mudaraddi requested changes
looks good - but really this isn't complete until you add arg-parse and read from parameters 
https://docs.python.org/3/library/argparse.html

2023-11-06 10:42 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +    f.close()
you're hardcoding this filepath - you should allow user to enter a filepath via an function parameter 
i.e.
```
from pathlib import Path

def create_file(dirpath):
     """
    makes a txt file for the results to be returned into called output.txt in directory filepath given
    :param: a string representing a directory path
    """
    f = open(Path(filepath / "output.txt"), "w")
    f.close()

2023-11-06 10:42 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +def create_file():
you should add a test for this function - look at mocking open

2023-11-06 10:42 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +    main(netbox_filepath, reverse_order=False)
we're going to need to add argparse to this so we can read in command-line arguments - that's the next job. 

Currently the user of this script needs to modify values here to use it properly. Instead we want the user to be able to specify arguments via the command line when calling the script i.e.

`python get_dns_records.py --netbox_filepath "/path/to/file.xlsx" --reverse True` etc

2023-11-06 16:02 UTC, khalford requested changes
You should move `.github/workflows` to the top level directory.

2023-11-06 16:02 UTC, khalford commented on .gitignore
> +!reverseforwardrecord/.github/workflows/get_dns_records.yaml
```suggestion
.idea/
__pycache__/
venv/
.vscode/
```

2023-11-06 16:02 UTC, khalford commented on .gitignore
> +!reverseforwardrecord/.github/workflows/get_dns_records.yaml
It's better to ignore the files you don't want than to ignore everything except the files you do want.

2023-11-08 11:18 UTC, dev-0pz commented on .gitignore
> +!reverseforwardrecord/.github/workflows/get_dns_records.yaml
no because sensitive information file names change around so it is safer to do it this way

2023-12-06 14:30 UTC, DavidFair commented
@dev-0pz Can you see if we can get this moving again?

2024-06-05 10:22 UTC, khalford commented
Closing due to inactivity. Can be reopened if picked up again.

2024-06-05 10:22 UTC, closed without merging