Terra meerkat
stfc/cloud-ops-tools pull request #13
Opened 2024-01-12 10:35 UTC by Chris-green-stfc

Moved VM creation / deletion from ansible to terraform, for better error handling.
The storage benchmarking now points to a victoria metrics DB.

2024-01-19 10:14 UTC, anish-mudaraddi commented on AnsiblePlaybooks/meerkat/deploy.tf
> +}
some strange formatting here - please check

2024-01-19 10:18 UTC, anish-mudaraddi commented on AnsiblePlaybooks/meerkat/roles/storage_benchmark/files/benchmark.sh
> +s=1
reading further into this - it looks like you run 3 benchmarking scripts in one here - see my comment on splitting it up

2024-01-22 10:26 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/storage_benchmark/files/benchmark.sh
> +curl -H 'Content-Type: application/json' -d '{"metric":"sequential_write","value":"'$sys_seqw_1'","tags":{"flavor":"'$flavor'", "image":"'$image'","test_type":"kb", "storage_type":"local"}}' http://1
This is an openstack IP address, so will never change

2024-01-22 10:27 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/storage_benchmark/files/benchmark.sh
> +server_UUID=$(curl  http://169.254.169.254/openstack/latest/meta_data.json -s  | grep -ioP .{8}-.{4}-.{4}-.{4}-.{12})
This is an openstack constant IP address, so will never change

2024-01-22 10:27 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/storage_benchmark/files/benchmark.sh
> +#!/bin/bash
I have combined the benchmarks into one function, that is called 3 times. This way it is easier to add/alter tests

2024-01-22 10:42 UTC, anish-mudaraddi requested changes
looks good - you've got a typo :)

2024-01-22 10:42 UTC, anish-mudaraddi commented on AnsiblePlaybooks/meerkat/meerkat.yaml
> +    - role: setup_torage_benchmark
typo

2024-01-22 10:42 UTC, anish-mudaraddi commented on AnsiblePlaybooks/meerkat/roles/setup_storage_benchmark/files/benchmark.sh
> +#!/bin/bash
This is a lot better - great work :+1:

2024-01-22 10:42 UTC, anish-mudaraddi commented on AnsiblePlaybooks/meerkat/roles/setup_storage_benchmark/files/benchmark.sh
> +DB="http://172.16.101.186:4242/api/put"
I'm happy to leave this as is for now - but in future you shouldn't hardcode the IPs. 

We should instead get it as an input when calling the script like so: 
```
# start of script
DB_IP=$1  #first argument to benchmark script
DB_PORT=$2 #second argument to benchmark script
...
DB="http://${DB_IP}:${DB_PORT}/api/put"
```

Makes it easier to change later - we can have them be a variable in Ansible like so;
```
- name: Run benchmark
  shell: ./benchmark.sh {{ db_ip }} {{ db_port }}
  register: script_output
```

You can leave this for a future PR when we need to change it

2024-01-22 10:46 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/setup_storage_benchmark/files/benchmark.sh
> +DB="http://172.16.101.186:4242/api/put"
This IP address will change. I plan to add in the variables like this to my next PR, with templating files.

2024-01-22 10:48 UTC, anish-mudaraddi approved these changes

2024-01-22 10:50 UTC, merged