Finalise initial ansible-cumulus set of plays
stfc/cloud-ops-tools pull request #18
Opened 2024-02-05 14:14 UTC by apdibbo

Finalise initial host inventories

Fix issue of hosts never getting marked as bootstrapped

Remove unneeded code

2024-02-12 10:28 UTC, apdibbo commented on AnsiblePlaybooks/ansible-cumulus/host_vars/lfsw15.r26.cloud.internal.yml
> -bootstrapped: false
Done

2024-02-12 14:18 UTC, DavidFair requested changes

2024-02-12 14:18 UTC, DavidFair commented on AnsiblePlaybooks/ansible-cumulus/common/tasks/read_host_inventory.yml
> +    ansible_connection: paramiko
Can we set this in `group_vars/all.yml`:

```
ansible_connection: paramiko```

In `host_vars/localhost` we'll want to override this with 
`ansible_connection: local`

That way we don't have to remember to write parakimo everywhere

2024-02-12 14:18 UTC, DavidFair commented on AnsiblePlaybooks/ansible-cumulus/roles/bridge/tasks/main.yml
> +    vlan_mappings: "{{ vlan_mappings|default(
Nit: could we add a comment saying what format we're going into, e.g.

"Make a list of dictionaries containing the bridge ID mapped to ..." since this is terrible to read but foisted on us until upstream learns how to PATCH in-place

2024-02-12 14:18 UTC, DavidFair commented on AnsiblePlaybooks/ansible-cumulus/roles/evpn/tasks/main.yml
> +      configured_evpn: true
This won't persist between runs? If this is required we should add a check which sets this flag based on if some conditions related to the eVPN are true

2024-02-12 14:22 UTC, apdibbo commented on AnsiblePlaybooks/ansible-cumulus/common/tasks/read_host_inventory.yml
> +    ansible_connection: paramiko
I'd rather it be explicit what is used within the plays/roles

2024-02-12 14:23 UTC, apdibbo commented on AnsiblePlaybooks/ansible-cumulus/roles/evpn/tasks/main.yml
> +      configured_evpn: true
Yes it does, see the write right below it:

`- ansible.builtin.include_tasks: "common/tasks/write_host_inventory.yml"`

2024-02-12 14:27 UTC, Chris-green-stfc commented on AnsiblePlaybooks/ansible-cumulus/roles/reinstall/tasks/main.yml
> +    name: "{{ansible_host}}"
name: "{{ansible_host}}" should be changed to name: "{{ ansible_host }}"

2024-02-12 14:28 UTC, apdibbo commented on AnsiblePlaybooks/ansible-cumulus/roles/reinstall/tasks/main.yml
> +    name: "{{ansible_host}}"
Hm, yamllint didnt pick that up

2024-02-13 09:45 UTC, apdibbo commented on AnsiblePlaybooks/ansible-cumulus/roles/reinstall/tasks/main.yml
> +    name: "{{ansible_host}}"
Sorted now

2024-02-13 09:50 UTC, apdibbo commented on AnsiblePlaybooks/ansible-cumulus/roles/bridge/tasks/main.yml
> +    vlan_mappings: "{{ vlan_mappings|default(
I've added a line to the readme referring to the upstream docs

2024-02-15 16:24 UTC, DavidFair approved these changes

2024-02-15 16:24 UTC, merged