Added Meerkat benchmarking
stfc/cloud-ops-tools pull request #2
Opened 2023-10-05 12:06 UTC by Chris-green-stfc

added ansible code for creating and destroying VM, and code for storage benchmarks.

2023-10-09 14:56 UTC, Chris-green-stfc commented
Added Meerkat creation and deletion of VMs, and updated codebase to contain ansible roles/tasks.

2023-10-10 08:44 UTC, DavidFair requested changes

2023-10-10 08:44 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/meerkat.yaml
> +
Nit: Can we reduce the indentation

2023-10-10 08:44 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/meerkat.yaml
> +                    ram: "<200000"
Can we move this to a var instead?

2023-10-10 08:44 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/meerkat.yaml
> +                    flavor_list_search: 'g-'
I would simplify this:

```flavors: "{{ flavors | reject('search', 'g-') | list }}"```

Since the task is bespoke enough I think the variable is fairly bespoke

2023-10-10 08:44 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/storage_benchmark/tasks/create_vm.yaml
> +      key_name: diz41711
Can we move this to a playbook var?

2023-10-10 08:44 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/storage_benchmark/tasks/create_vm.yaml
> +      name: "Meerkat_L7WZTzJZ"
Can we use a randomly generated name, something along the lines of:

```
set_fact: machine_name: "meerkat_{{ lookup('community.general.random_string', length=4) }}
```

2023-10-10 08:44 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/storage_benchmark/tasks/create_vm.yaml
> +      availability_zone: ceph
We shouldn't need to specify ceph here

2023-10-10 12:48 UTC, merged