Merge manila
stfc/cloud-ops-tools pull request #24
Opened 2024-03-13 16:23 UTC by Chris-green-stfc

Ready to test

2024-03-15 11:48 UTC, khalford commented on AnsiblePlaybooks/meerkat/deploy.tf
> +    }
```suggestion
    provisioner "file" {
            source      = "./script.sh"
            destination = "/tmp/script.sh"
        }
      provisioner "remote-exec" {
      inline = [ "sudo bash /tmp/script.sh" ]
      }
```

2024-03-15 11:55 UTC, khalford requested changes
Haven't tested the deployment but I've made comments about the code.

2024-03-15 11:55 UTC, khalford commented on AnsiblePlaybooks/meerkat/roles/attach_manila/tasks/main.yaml
You should be able to put all of these tasks under `tasks` then you can leave `become: true` at the top and not have to repeat it:
```
---
- tasks:
   become: true
   - name: some task
   
  - name:: some other task
   
```

2024-03-15 11:55 UTC, khalford commented on AnsiblePlaybooks/meerkat/variables.tf
> +    description = "The size of the volume to commission"
```suggestion
    description = "The size of the volume to commission in GB"
```

2024-03-20 10:17 UTC, AdamG412 commented on AnsiblePlaybooks/meerkat/variables.tf
In total you have to put your username in 4 places manually during setup - twice here, once in vars/storage.yaml and once as a key name with the run_meerkat script. We should just reuse this variable

2024-03-20 10:17 UTC, AdamG412 commented on AnsiblePlaybooks/meerkat/variables.tf
Setup instructions should also go in the readme, along with any requirements (ansible, terraform etc.) that need to be installed

2024-03-25 10:17 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/deploy.tf
> +    }
Moved into ansible

2024-03-25 10:18 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/attach_manila/tasks/main.yaml
I don't want to blanket sudo, I prefer to sudo only when necessary

2024-03-25 10:19 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/variables.tf
I will do this in a future PR

2024-03-25 14:35 UTC, khalford approved these changes
LGTM

2024-03-25 14:47 UTC, DavidFair requested changes

2024-03-25 14:47 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/vars/storage.yaml
> +user: <user>
What user does it refer to, e.g. fed ID or the user on the machine?

2024-03-25 14:47 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/deploy.tf
>  resource "null_resource" "ansible_playbook" {
This is racey? Since it isn't blocked by any of the other resources being a null resource
Can we not put this provisioner with the VM block?

2024-03-25 14:47 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/deploy.tf
>    volume_id = local.volume_ids[count.index]
Can we not reference this at VM creation time? That simplifies the flow since otherwise the provisioner has to potentially move here

2024-03-25 14:47 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/deploy.tf
> +
Nit, can we tidy this whitespace up

2024-03-25 14:47 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/attach_manila/tasks/main.yaml
> +  shell: chown diz41711 /mnt/manila{{ vm_count }}
This should be `ansible_user` instead of your fed ID
That way it automatically picks up if we're using `ubuntu` or `rocky`

2024-03-25 14:47 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/run_storage_benchmark/tasks/main.yaml
> +- name: Run local benchmark
Nit: `local` -> `local storage`
Since I originally read it as run the benchmark locally (e.g. this machine)

2024-03-25 14:47 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/setup.sh
> +pip install ansible
We need to create a venv before potentially trashing the user's pip env - this will break in 22.04+ to specifically prevent this pattern

```
sudo apt install -y python3-openstackclient python3-pip python3-venv
python3 -m venv venv
source venv/bin/activate
pip install ansible
# ...
```

2024-03-25 14:47 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/setup.sh
> +pip install ansible
All the requirements should be in a `requirements.txt` file that is simply installed with `pip install -r requirements.txt`

2024-03-25 14:47 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/setup.sh
> +ansible-galaxy collection install ansible.posix
These should go into a requirements.yml file then install with `ansible-galaxy collection install -r requirements.yml`

2024-03-25 14:47 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/variables.tf
> +    default  = "keyless"
Can we drop this default? If nothing was specified it should fail with an error saying unset rather than it saying "the key 'keyless' doesn't exist"

2024-03-25 14:47 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/variables.tf
> +    default = 11
Nit: why 11? I would unify the share and volume size since they should run the same underlying benchmark, therefore require the same space

2024-04-02 08:17 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/setup.sh
> +pip install ansible
future PR

2024-04-03 08:48 UTC, DavidFair commented
You have merge conflicts, I'm happy to re-review when they've got resolved

2024-04-03 08:54 UTC, Chris-green-stfc commented
Conflicts resolved

2024-04-23 09:42 UTC, DavidFair requested changes

2024-04-23 09:42 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/attach_manila/tasks/main.yaml
> +  shell: chown {{ user }} /mnt/manila{{ vm_count }}
Use the Ansible module: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html#examples

2024-04-29 08:48 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/variables.tf
> +    default = "/home/<user>/cloud-ops-tools/AnsiblePlaybooks/meerkat/meerkat.yaml"
This cannot be changed, due to terraform running this command. When testing `{{ ANSIBLE_USER }}` was not replaced, so it failed to run

2024-04-29 09:40 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/attach_manila/tasks/main.yaml
> +  shell: chown {{ user }} /mnt/manila{{ vm_count }}
Changed as suggested

2024-04-29 10:18 UTC, DavidFair approved these changes

2024-04-29 10:19 UTC, merged