Added lightweight CPU benchmarks
stfc/cloud-ops-tools pull request #27
Opened 2024-06-19 10:24 UTC by Chris-green-stfc

Added rust-based CPU benchmarks which can be run on all VM flavors

2024-06-19 12:46 UTC, anish-mudaraddi approved these changes

2024-06-19 14:55 UTC, meoflynn requested changes

2024-06-19 14:55 UTC, meoflynn commented on AnsiblePlaybooks/meerkat/roles/cpu_rust/templates/run_benchmark.sh.j2
> +curl -d 'cpu_rust,image='"$image"',flavor='"$flavor"',test_type='fft_multi' 'result'='"$fft_multi"'' -X POST $DB
I think we should not have this address hardcoded

2024-08-21 13:38 UTC, meoflynn approved these changes

2024-08-21 13:40 UTC, merged