Ip checker
stfc/cloud-ops-tools pull request #28
Opened 2024-07-23 15:01 UTC by dev-0pz

added an ip and dns resolver that has its own unit tests which are used to grab the ips from the files after being displayed out in a reverse/ forward order format and then tested on which ips/dns are reachable

2024-07-30 11:54 UTC, anish-mudaraddi requested changes
first pass through - will look at tests after

2024-07-30 11:54 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +
don't think you need this function - you can replace this with a one-liner like so: 
```python
open(out_filepath, 'w').close()
```

2024-07-30 11:54 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +            )  #
probably good to have a comment about what this does

2024-07-30 11:54 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +            idrac = idrac.rsplit(".", 1)[0]
here's a much cleaner way to do the same thing
```suggestion
            ip_components = item["idrac_ip"].split(".")
            ip_components = ip_components[:1][::-1] # remove first octet and reverse ip
            idrac = '.'.join(ip_components) 
```

2024-07-30 11:54 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +    print(output_filepath)
remove this  - we can add logging later

2024-07-30 11:54 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +                out_file.write(f"{item['hypervisor']}\tIN A\t{item['ip_address']}\n")
whenever you open() a file to write to it we prohibit other processes from accessing that file. Therefore we need to be considerate to others and ensure that we process the file as quick as possible. 
Here, we are doing some processing WHILST the file is open - which can be done before we open the file - making writing quicker. Here's an example of how we can make this quicker: 

```suggestion
   lines = []
   for item in parsed_info:
            if reverse_order:
                lines.append(f"{item['ip_address']}\tIN PTR\t{item['hypervisor']}\n")
            else:
                lines.append(f"{item['hypervisor']}\tIN A\t{item['ip_address']}\n")

    with open(output_filepath, "w", encoding="utf-8") as out_file:
        outfile.writelines(lines)
```

2024-07-30 11:54 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +            unreachable_dns.append(dns_name)
This is more efficient 

```suggestion
    reachable_ips = list(filter(is_reachable_ip, ips_found))
    unreachable_ips = [ip for ip in ips_found if ip not in reachable_ips]

    reachable_dns = list(filter(is_reachable_dns, dns_found))
    unreachable_dns = [dns for dns in dns_found if dns not in reachable_dns]
```

2024-07-30 11:54 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +    return reachable_ips, unreachable_ips, reachable_dns, unreachable_dns
it feels like you should use a dataclass here - but we can add that later

2024-07-30 11:54 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +    create_file(output_filepath)
you don't need this function - see above
```suggestion
    open(out_filepath, 'w').close()
```

2024-07-30 11:54 UTC, anish-mudaraddi commented on reverseforwardrecord/get_dns_record.py
> +    check_ip(reverse_order, output_filepath)
you can probably delete this line - I think its a bug since you call `check_ip` later on and you don't do anything with the results here

2024-08-05 10:10 UTC, khalford requested changes
LGTM, few comments

2024-08-05 10:46 UTC, dev-0pz commented on .gitignore
> +!reverseforwardrecord/.github
thanks ill give it a try and let you know

2024-08-08 14:17 UTC, dev-0pz commented on reverseforwardrecord/get_dns_record.py
> +            idrac = idrac.rsplit(".", 1)[0]
doesn't work replaces all the ips with the number 10

2024-08-08 14:19 UTC, dev-0pz commented on reverseforwardrecord/get_dns_record.py
> +    print(output_filepath)
removed print(output_filepath)

2024-08-08 14:23 UTC, dev-0pz commented on reverseforwardrecord/get_dns_record.py
> +                out_file.write(f"{item['hypervisor']}\tIN A\t{item['ip_address']}\n")
very helpful thank you

2024-08-08 14:47 UTC, dev-0pz commented on .gitignore
> +!reverseforwardrecord/.github
couldnt find a way to do it

2024-08-08 14:49 UTC, dev-0pz commented on reverseforwardrecord/get_dns_record.py
> +
requires a lot of changing to unit test code

2024-08-08 14:49 UTC, dev-0pz commented on reverseforwardrecord/get_dns_record.py
> +            )  #
done

2024-08-08 14:49 UTC, dev-0pz commented on reverseforwardrecord/get_dns_record.py
> +            unreachable_dns.append(dns_name)
done

2024-08-08 15:08 UTC, dev-0pz commented on reverseforwardrecord/.github/workflows/get_dns_records.yaml
> +    runs-on: ubuntu-20.04
done

2024-08-08 15:15 UTC, dev-0pz commented on reverseforwardrecord/get_dns_record.py
> +            )
it already shows both as an error if debugging is needed

2024-08-21 13:52 UTC, anish-mudaraddi approved these changes

2024-09-02 09:46 UTC, khalford requested changes
LGTM - Once pylint is passing I'm happy to approve

2024-09-13 06:37 UTC, khalford approved these changes

2024-09-13 06:37 UTC, merged