Added Unix benchmark
stfc/cloud-ops-tools pull request #32
Opened 2024-08-28 09:09 UTC by Chris-green-stfc

Added unix-bench for more CPU/system benchmarking

2024-08-28 12:13 UTC, meoflynn requested changes

2024-08-28 12:13 UTC, meoflynn commented on AnsiblePlaybooks/meerkat/roles/unix-bench/templates/extract_results.sh.j2
> +#hypervisor=$(echo $vm_info | grep -ioP "\w*.nubes.rl.ac.uk" | head -1)
Why is this line commented out?

2024-08-28 12:17 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/unix-bench/templates/extract_results.sh.j2
> +#hypervisor=$(echo $vm_info | grep -ioP "\w*.nubes.rl.ac.uk" | head -1)
It is there in case we ever want HV information, but it requires admin creds to do so

2024-08-28 15:49 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/unix-bench/templates/extract_results.sh.j2
> +        curl -H "Authorization: Basic `echo -n "{{ db_username }}:{{ db_password }}" | base64`" -d 'unix_bench,image='"$image"',flavor='"$flavor"' '"$bench1"'='"$r1"'' -X POST $DB --insecure
If the host has an invalid cert we can get a proper DNS record and TLS certificate?
That way we don't have to use the `--insecure` flag going forward

2024-08-28 15:49 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/unix-bench/templates/extract_results.sh.j2
> +
`set -euo pipefail` so it will fail if something goes wrong

Additionally can we setup shell-check like so: https://github.com/stfc/SCD-OpenStack-Utils/blob/master/.github/workflows/gpu_benchmark.yaml#L11

Since this more scripts we add without linting the harder it will be in the future

2024-08-28 15:49 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/unix-bench/templates/extract_results.sh.j2
> +vm_info=$(openstack server show $server_UUID --os-cloud openstack)
Can we get this from the same `meta_data.json` or cloud-init which should contain all the relevant details rather than having to copy app creds to each VM

2024-09-10 08:57 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/unix-bench/templates/extract_results.sh.j2
> +vm_info=$(openstack server show $server_UUID --os-cloud openstack)
Will address this in future PR

2024-11-28 14:23 UTC, closed without merging