Hepscore benchmark
stfc/cloud-ops-tools pull request #4
Opened 2023-10-16 14:17 UTC by AdamG412

Added role to run the HEPScore benchmark on VMs created by Meerkat. Also provides a framework which can be extended to run other benchmarks.

2023-12-07 22:42 UTC, DavidFair requested changes

2023-12-07 22:42 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/README.md
> +Meerkat requires Openstack credentials to create or delete VMs. These can be given by downloading and sourcing an openstackrc.sh file, but this requires password input and is not suitable for running
Lets not mention this, I want us to move to app creds / clouds.yaml by default

2023-12-07 22:42 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/README.md
> +- `harbor_username` and `harbor_password`
Why do we need Harbor creds? Surely the image is public

2023-12-07 22:42 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/README.md
> +    - The name of the user to log into VMs as
I'd simply hardcode this as `ubuntu` or `rocky` depending on the OS we deploy and drop this from the README

2023-12-07 22:42 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/meerkat.yaml
> +            - "{{ flavor_list.flavors }}"
Do we need this, if we can't get a flavour list the chances are we're not going to be able to make a VM

2023-12-07 22:42 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/create_vm/tasks/main.yaml
> +        vm_IP: "{{ vm_info.server.addresses.Internal[0].addr }}"
Ditto, I don't get why we need this rescue block?

2023-12-07 22:42 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/hepscore/tasks/main.yml
> +        dest: ~/send_to_victoria.sh
This should go into `/usr/local/bin` as a custom binary as per UNIX conventions

2023-12-07 22:42 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/hepscore/tasks/main.yml
> +        state: present
Do we need an equiv for rocky?

2023-12-07 22:42 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/hepscore/tasks/main.yml
> +        msg: HEPScore failed to run for flavor {{ vm_flavor }} image {{ vm_image }}
Don't try and rescue, let Ansible propagate the error as you're likely throwing away the underlying error with your custom error making it difficult to troubleshoot the block

2023-12-07 22:42 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/hepscore/templates/send_to_victoria.sh.j2
> +#!/bin/bash
We should set this to fail if something goes wrong (https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425)

```
#!/bin/bash
set -euo pipefail
```

2023-12-07 22:42 UTC, DavidFair commented on AnsiblePlaybooks/meerkat/roles/hepscore/templates/send_to_victoria.sh.j2
> +curl -H 'Content-Type: application/json' -d '{"metric":"hepscore","value":"'$SCORE'","tags":{"flavour":"{{vm_flavor}}", "image": "{{ vm_image }}"}}' {{victoria_url}}
Does victoria metrics automatically put in the timestamp, or is it worth pulling this out of the JSON / file creation time?

2023-12-11 08:16 UTC, AdamG412 commented on AnsiblePlaybooks/meerkat/roles/create_vm/tasks/main.yaml
> +        vm_IP: "{{ vm_info.server.addresses.Internal[0].addr }}"
This (and the above is a strange issue I've been running in to where ansible will return a slightly different object for some reason -  the structure is the same apart from "openstack" being replaced by "server". @Chris-green-stfc hasn't run into this, but I've had both be returned and I haven't been able to pin down why.

2023-12-11 08:22 UTC, AdamG412 commented on AnsiblePlaybooks/meerkat/roles/hepscore/templates/send_to_victoria.sh.j2
> +curl -H 'Content-Type: application/json' -d '{"metric":"hepscore","value":"'$SCORE'","tags":{"flavour":"{{vm_flavor}}", "image": "{{ vm_image }}"}}' {{victoria_url}}
It does yes

2023-12-11 08:48 UTC, AdamG412 commented on AnsiblePlaybooks/meerkat/roles/hepscore/tasks/main.yml
> +        msg: HEPScore failed to run for flavor {{ vm_flavor }} image {{ vm_image }}
The issue with this is that when VMs fail like this is that they don't get deleted, because the deletion step runs on localhost and so you can't put that in the rescue. This will leave VMs hanging around, filling the project quota and bringing the whole system down fairly quickly unless you manually catch it. I haven't been able to come up with a great solution for this, but I know that @Chris-green-stfc  has been looking at terraform which will hopefully be able to get around this.

2023-12-11 08:51 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/hepscore/tasks/main.yml
> +        msg: HEPScore failed to run for flavor {{ vm_flavor }} image {{ vm_image }}
I am currently running `terraform destroy --auto-approve && terraform plan -out=deploy.tfplan && terraform apply "deploy.tfplan"` which should destroy all the VMs it controls before spinning up new ones.

2023-12-11 08:58 UTC, AdamG412 commented on AnsiblePlaybooks/meerkat/roles/hepscore/tasks/main.yml
> +        state: present
I don't think so, on our rocky images you can just `dnf install apptainer`.  It's in the `epel-release` repositories (see [docs](https://apptainer.org/docs/admin/main/installation.html#install-rpm-from-epel-or-fedora).

2023-12-11 11:42 UTC, Chris-green-stfc approved these changes

2023-12-11 12:06 UTC, merged