Integrating Iris GPU benchmarking with meerkat
stfc/cloud-ops-tools pull request #41
Opened 2024-11-19 11:25 UTC by Barfy007JB1

This PR integrates IRIS GPU benchmarking functionality into Meerkat.

2024-11-19 15:41 UTC, Chris-green-stfc requested changes
Looks good overall. The ansible stuff is good, just needs some tidying up of the bash script(s).

2024-11-19 15:41 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/meerkat.yaml
> +- hosts: all
This should be `- hosts: gpu` that way it will only be run when people want to run the GPU benchmarks

2024-11-19 15:41 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/setup_iris/files/get-iris.sh
> +  git clone https://github.com/bryceshirley/iris-bench.git
Can we change this to the new repo location? 
https://github.com/Chris-green-stfc/iris-bench.git

2024-11-19 15:41 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/setup_iris/files/get-vm-info.sh
> +echo $vm_info | grep -ioP "image\s\|\s\S*" | cut -c 9-
This file doesn't seem to be run. So does it need to be here?

2024-11-19 15:41 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/setup_iris/templates/gpu_benchmark.sh.j2
> +cp get-iris.sh $storage_path
`$storage` doesn't seem to be a declared variable.
Does the file need to be copied anywhere? It should have already have been copied to ~/

2024-11-19 15:41 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/setup_iris/tasks/main.yaml
> +    - get-vm-info.sh
Does this file need to be copied? I don't think it is called at all

2024-12-09 12:14 UTC, khalford requested changes

2024-12-09 15:37 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/setup_iris/files/get-iris.sh
> +  mkdir iris_bench
Had a discussion with Kaleb. instead of hardcoding the path, just add a comment with the directory that the script is run in
# Expected run location:
# /home/<user>

2024-12-10 16:05 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/setup_iris/templates/gpu_benchmark.sh.j2
> +image=$(echo $vm_info | grep -ioP "image\s\|\s\S*" | cut -c 9-)
Not needed as it is repeated below

2024-12-10 16:06 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/setup_iris/templates/gpu_benchmark.sh.j2
> +image=$(echo $vm_info | grep -ioP "image\s\|\s\S*" | cut -c 9-)
With the latest version of meerkat this information is passed from terraform to ansible. So this can be replaced with `flavor="{{ flavor }}"
image="{{ image }}"`

2024-12-10 16:07 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/setup_iris/templates/gpu_benchmark.sh.j2
> +	curl -H "Authorization: Basic `echo -n "{{ db_username }}:{{ db_password }}" | base64`" -d 'gpu_benchmark,image='"$image"',flavor='"$flavor"',test_type='${benchmark} Emisions' 'result'='"$gpu_emisio
As the DB has now been set up properly, `--insecure` is no longer needed

2024-12-10 16:12 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/setup_iris/files/get-iris.sh
> +  cd /home/<user>
You shouldn't need to create a directory under `/home` as it should be there by default. If you want to tell the user where it runs, then maybe put something like `#Expected run location: /home/<user>`

2024-12-12 09:24 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/setup_iris/templates/gpu_benchmark.sh.j2
> +hypervisor=$(echo $vm_info | grep -ioP "\w*.nubes.rl.ac.uk" | head -1)
You don't need these 3 lines, as they were only there to get the image and flavor data. And the hypervisor data wont work without admin creds (which we wont be using with meerkat)

2024-12-12 09:24 UTC, Chris-green-stfc commented on AnsiblePlaybooks/meerkat/roles/setup_iris/templates/gpu_benchmark.sh.j2
> +	curl -H "Authorization: Basic `echo -n "{{ db_username }}:{{ db_password }}" | base64`" -d 'gpu_benchmark,image='"$image"',flavor='"$flavor"',test_type='${benchmark} Emisions' 'result'='"$gpu_emisio
Is "$gpu_emissions_" a typo? Should it be "$gpu_emissions"?

2025-01-14 11:20 UTC, Chris-green-stfc commented
LGTM

2025-01-14 11:22 UTC, Chris-green-stfc approved these changes

2025-02-06 07:50 UTC, khalford approved these changes

2025-02-06 07:50 UTC, merged