Create directory for random tools
stfc/cloud-ops-tools pull request #46
Opened 2024-12-13 07:51 UTC by jose-caballero

Create a misc/ directory to collect small random tools. They are tools that only need a single file and, therefore, a entire directory for each one of them would be an overkill.

Populate this new directory misc/ with a first tool and a README file.

The README file should explain briefly what each tool in this directory does.

The first tool being added is txt2pdf.py

2024-12-13 10:10 UTC, khalford requested changes
I have added some comments about making the script easier to understand and use. Feel free to ignore them all or come ask me for understanding / help

2024-12-13 10:10 UTC, khalford commented on misc/txt2pdf.py
Have you ever used [argparse](https://docs.python.org/3/library/argparse.html)? I think that would be a good fit for this script. Argparse would allow you to use the script in the following way:
Of course you can always just use `sys.argv` module but argparse allows us to have nice parameters and `--help` arguments built in.
```shell
# python3 txt2pdf.py <input_filename> <output_filename>
# e.g.
python3 txt2pdf.py my_text.txt my_text.pdf

# or

python3 txt2pdf.py --input my_text.txt --output my_text.pdf
```

2024-12-13 10:15 UTC, jose-caballero commented
I will have a look to the suggestions. Some are to correct typos :(

2024-12-13 11:31 UTC, azahmd approved these changes

2024-12-19 08:46 UTC, khalford requested changes
Some more comments about best practice. But this is already much easier to use / understand than before

2024-12-19 08:46 UTC, khalford commented on misc/txt2pdf.py
>          print(f"Error occurred: {e}")
We don't need to catch every error only to throw it again with no additional information. You should remove this statement and only use try except where we can gain more useful information

2024-12-19 08:46 UTC, khalford commented on misc/txt2pdf.py
>          print(f"Error occurred: {e}")
Additionally, by removing this try except block we can de-indent the code which is cleaner

2024-12-19 08:46 UTC, khalford commented on misc/txt2pdf.py
Can you use the **reST** docstring format for all the functions in this code? It's what we use in our code.

Below is an example from your code:
```python
from typing import List
def parse_markdown(input_text: str) -> List:
    """
    Parses the input markdown text and converts it into a list of ReportLab flowables.
    :param input_text: The input text containing markdown-like syntax.
    :returns: A list of ReportLab flowables (text, tables, etc.) to be included in the PDF.
    """
```

2024-12-19 08:46 UTC, khalford commented on misc/txt2pdf.py
> +        return
There is not much benefit to checking the path exists here then printing and returning. I would remove this statement and let the code raise an exception naturally. If you want to catch this then I would raise and exception instead of print and return. E.g.
```suggestion
    if not os.path.exists(input_file):
        raise ValueError(f"Error: File '{input_file}' not found.")
        # or
        raise RuntimeError(f"Error: File '{input_file}' not found.")   
```
But again, you don't gain any more information from catching and raising your own error than you do letting the code raise it's own error

2024-12-19 08:46 UTC, khalford commented on misc/txt2pdf.py
> +        print(f"Error occurred: {e}")
It is bad practice to catch every error then re-raise it. You should be making `except` blocks for specific errors or none at all.
I will leave some suggestions below:
**Best practice** to catch specific errors and re-raise with more detailed information.
```suggestion
    except SomeError as exc:
        raise MyCustomException("This specific error occured...") from exc
    except SomeOtherError as exc:
        raise MySecondCustomException("This other specific error occured...") from exc
```
**or**
If you really want to catch each error and make it look pretier. Note the raise ... **from** exc
```suggestion
    except Exception as exc:
        raise MyCustomException("There was an error when attempting to convert your file. See further for details:") from exc
```
**or**
Remove the statment and let the code error naturally is still better than catching every exception and re-throwing with no additional information
```suggestion
```

2024-12-19 08:46 UTC, khalford commented on misc/txt2pdf.py
> +    print(output_filename)
Can these be more informative or remove entirely.
```suggestion
    print(f"Taking file {input_filename} as the input file.")
    print(f"Will output to {output_filename}")
```

2024-12-19 08:46 UTC, khalford commented on misc/txt2pdf.py
> +        print(f"Error occurred: {e}")
This is related to the below comment about exceptions.

It is cleaner to make try blocks as small as possible. Only put code we expect to error inside a try block because then we can catch exceptions.

Why does any of this code need to be inside a try block? We are already checking if the path exists above this.

```suggestion
    with open(input_file, 'r', encoding='utf-8') as f:
        input_text = f.read()

    flowables = []  # List to store elements for the PDF

    # Add a title page with the current date
    date_str = datetime.now().strftime('%Y-%m-%d')
    title = Paragraph("Cloud Operations Report", ParagraphStyle('Title', fontSize=36, alignment=TA_CENTER))
    date = Paragraph(date_str, ParagraphStyle('Date', fontSize=24, alignment=TA_CENTER))
    flowables.extend([Spacer(1, 100), title, Spacer(1, 50), date, PageBreak()])

    # Parse the markdown content and add to flowables
    flowables.extend(parse_markdown(input_text))

    # Create and build the PDF document
    doc = SimpleDocTemplate(
        output_file,
        pagesize=LETTER,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72,
    )
    doc.build(flowables)
```

2024-12-19 08:46 UTC, khalford commented on misc/txt2pdf.py
> +from reportlab.lib.enums import TA_CENTER  # For center alignment of text
Should keep all imports from the same module together. Here I have moved the `reportlab.lib.enums` import to underneath `reportlab.lib.styles`

```suggestion
from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER  # For center alignment of text
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)
```

2024-12-19 08:46 UTC, khalford commented on misc/txt2pdf.py
Have you used the Black formatter on your code? It is a linter that we use to make everything cleaner and similar.
```shell
pip3 install black
black txt2pdf.py
# or
python3 -m black txt2pdf.py
```

2024-12-19 08:46 UTC, khalford commented on misc/txt2pdf.py
Similar to above. Have you used Pylint on your code? Pylint is very useful to standarise code however it will not make changes for you. You will have to change your code by following the warnings. It is ideal to have Pylint score you 10/10 on your code.
```shell
pip3 install pylint
pylint txt2pdf
# or
python3 -m pylint txt2pdf.py
```

2024-12-21 14:56 UTC, closed without merging

2024-12-21 14:57 UTC, jose-caballero commented
Somehow this PR got mixed commits. Starting from scratch is a quick and dirty solution, but also the most pragmatic.