Added ansible demo playbook
stfc/cloud-ops-tools pull request #6
Opened 2023-10-20 12:19 UTC by Chris-green-stfc

ansible demo for installing docker and NGINX for advanced workshop.

2023-10-24 16:01 UTC, DavidFair requested changes

2023-10-24 16:01 UTC, DavidFair commented on AnsiblePlaybooks/ansible-demo/staging
We should put some example IPs into this, e.g. `172.16.0.0` to show people how an inventory file looks

2023-10-24 16:01 UTC, DavidFair commented on AnsiblePlaybooks/ansible-demo/ansible-example.yaml
> +  - NGINX
Nit: lower case `nginx`

2023-10-24 16:01 UTC, DavidFair commented on AnsiblePlaybooks/ansible-demo/roles/create_vm/tasks/main.yaml
> +    key_name: diz41711
This vm name and key name needs to be set at the playbook, not role level to make it easy to re-use

2023-10-25 15:27 UTC, meoflynn requested changes
Could we add an example inventory to show how to use these playbooks?
The 172.16.0.0 would not work as it is currently

2023-12-06 14:29 UTC, DavidFair commented
@Chris-green-stfc is this worth still doing, since we now use dynamic inventories potentially? Either way would be good to get this in before we finish for Winter

2023-12-07 08:42 UTC, Chris-green-stfc commented
@DavidFair I updated the staging file, as suggested. I don't think I pinged in the PR channel though

2024-04-22 12:34 UTC, closed without merging